update

diff --git a/.bin/uniwatch b/.bin/uniwatch
--- a/.bin/uniwatch
+++ b/.bin/uniwatch
@@ -24,7 +24,7 @@ local_unison_dir=~/.unison/"${remote_ssh_handle}";
 # Validate arguments.
 
 if [[ -z "${remote_ssh_handle}" || ! -d "${local_unison_dir}" ]]; then
-	echo 'Invalid --remote-ssh-handle value: '"${remote_ssh_handle}"; exit 1;
+	echo 'Invalid --remote-ssh-handle: '"${remote_ssh_handle}"; exit 1;
 fi;
 
 # Run commands.
